--- 
apiVersion: v1
kind: Pod
metadata: 
  name: busybox
  namespace: default
spec: 
  containers: 
    - 
      command: 
        - sleep
        - "3600"
      image: busybox:latest
      name: busybox
