apiVersion: v1
kind: Pod
metadata:  
  name: busybox-sa
  namespace: default
spec: 
  serviceAccountName: jenkins
  containers:
  - image: busybox
    command: 
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
 
