apiVersion: v1
kind: Pod
metadata:
  name: curlpod
  namespace: web1
spec:
  containers:
  - image: curlimages/curl
    command: ["sleep", "9999999"]
    name: main
  - image: nginx
    name: nginx1
  restartPolicy: Always
