apiVersion : apps/v1
kind: Deployment
metadata:
  name: lb-deploy
  labels:
    app : myapp1  
    env: prod
    owner: baz
spec:
  replicas: 3
  selector:
    matchLabels: 
     project: bazprod
  template: 
   metadata:
    labels: 
      project: bazprod
   spec:
    containers:
     - name: baz-cont
       image: tomcat:latest
       ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: lb1-service
  labels:
   env: prod
   owner: baz
spec:
  selector:
    project: bazprod # selecting PODS with those labels
    ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetport: 80
  type: LoadBalancer

