apiVersion : apps/v1
kind: Deployment
metadata:
  name: lb-deploy
  labels:
    app : myapp1  
    env: prod
    owner: baz
spec:
  replicas: 3
  selector:
    matchLabels:  
     project: bazprod
  template: 
    metadata:
      labels: 
        project: bazprod # servie will look for those PODs labels
    spec:
       containers:
       - name: bazcont
         image: nginx:latest
         ports:
          - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: lb1-service
  labels:
    env: prod
    owner: baz
spec:
  type: LoadBalancer
  selector:
    project: bazprod # selecting PODS with those labels
  ports:
     - name: app-listener1
       protocol  : TCP
       port      : 80  # port on Loadbalancer
       targetPort: 80  # port on PODS 
