apiVersion: v1
kind: Pod
metadata:
  name: chown-pod
spec:
  containers:
  - name: chmod-container
    image: alpine
    command: ["/bin/sleep", "999999"]
    securityContext:
      capabilities:
        drop:
          - CHOWN
