---
apiVersion: v1
kind: Service
metadata:
  name: service-balance
  labels:
    env: prod
    owner: baz
spec:
  selector:
   project: bazprod  # selecting PODS with those  Labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 80  # port on load balancer
      targetPort: 80  #port on POD
    type: LoadBalancer
